### PR TITLE
Add commitish support

### PR DESCRIPTION
**Pull request by toruuetani**
I want to release any branch other than master.
So it would be nice if an option to specify commitish was available.

### CODE REVIEW

**Comment by toruuetani** [comment]
Sorry, mistake.

**Comment by tcnksm** [comment]
Thanks. 

I don't know we can create release with commitish not specific tag. Could you confirm it ? And if you can please show me example.  

And UI must be chaged,

```bash
$ git checkout <Hash>
$ # execute build...
$ ghr --commitish <artifact> # Use current commitish 
```

How do you think ?

**Comment by toruuetani** [comment]
We can create release with commitish(branch name). For example, 

- https://github.com/toruuetani/Chocolatey-Packages/releases/tag/winshot-1.53
- https://github.com/toruuetani/Chocolatey-Packages/releases/tag/winmerge-jp-2.14.0.68

These were released with commitish(branch name) by CircleCI.
Please check yaml and script.
- https://github.com/toruuetani/Chocolatey-Packages/blob/master/circle.yml
- https://github.com/toruuetani/Chocolatey-Packages/blob/master/release.sh

But I don't confirm with commitish (hash) , I will confirm it soon.

I don't think UI must be changed.
Because we still need release without commitish, it must work in the same way as the current.

**Comment by tcnksm** [comment]
Ah, I misunderstood what you want to do. Don't change UI.

**Comment by toruuetani** [comment]
I confirmed -c option with hash on https://github.com/toruuetani/ghr-commitish-example/releases .
See below releases.

- ```ghr -c another-branch "with-branch-name" <artifact>```

    https://github.com/toruuetani/ghr-commitish-example/releases/tag/with-branch-name

- ```ghr -c 4c4476683d37b375b5ad487ee803e9809c7924d2 "with-hash" <artifact>```

    https://github.com/toruuetani/ghr-commitish-example/releases/tag/with-hash

- ```ghr "without-commitish" <artifact>```

    https://github.com/toruuetani/ghr-commitish-example/releases/tag/without-commitish

**Comment by tcnksm** [comment]
Sorry for late, looks good. Please go ahead :+1:

**Comment by toruuetani** [comment]
Go ahead?
Please tell me what I should do.

**Comment by tcnksm** [comment]
I mean command line interface you show on the previous comments looks good. I want to see actual implementation. Or should I implement it ?

**Comment by toruuetani** [comment]
I already implemented that option.
So on my repository [toruuetani/ghr at feature-add-commitish-support](https://github.com/toruuetani/ghr/tree/feature-add-commitish-support), -c option works.

**Comment by tcnksm** [comment]
Could you check your pushed commit ?

**Comment by toruuetani** [comment]
At first I was confused too, but GitHubAPIOpts already supports commitish option (TargetCommitish).
So it was nice to just add -c option to "cli.go".

**Comment by tcnksm** [comment]
Ah, ok... Sorry I misunderstood too, because of WIP commit. 
I'll fix a little and merge it later. Thanks :+1:

**Comment by toruuetani** [comment]
Sorry for lack of explanation.
And thank you for your understanding!

**Comment by tcnksm** [comment]
Merged https://github.com/tcnksm/ghr/commit/15c3fe4ddc7d8dded38ba324343cb27201983e4a, thanks

**Pull request closed without merging**
