### PR TITLE
Added body option

### PR DESCRIPTION
**Pull request by jeppefrandsen**
Added -b option for describing a release

### CODE REVIEW

**Comment by tcnksm** [comment]
Thanks !

**Comment by jeppefrandsen** [comment]
Thank you! Can you create a new release with the changes?

**Comment by tcnksm** [comment]
Done to release https://github.com/tcnksm/ghr/releases/tag/v0.5.4
Please test it !

**Comment by jeppefrandsen** [comment]
Sorry for the late reply! Working great - thanks

**Comment by jeppefrandsen** [comment]
Would it BTW be ok to set Name = TagName when creating the release (also done in their example: https://developer.github.com/v3/repos/releases/). Sometimes we see that the heading is also including the PR name. Thanks

**Comment by tcnksm** [comment]
@jeppefrandsen yeah, it would be nice! I will work when I have time. But if you can, please PR!

**Comment by jeppefrandsen** [comment]
Will do. Change is a one-liner. But will test on our repositories to make sure it is fixed before doing a PR. Thanks a lot

**Pull request merged**
