### PR TITLE
Fix overlapping of DeleteRelease and CreateRelease

### PR DESCRIPTION
**Pull request by tchssk**
This is a same issue with #32.

### CODE REVIEW

**Comment by tcnksm** [comment]
Thanks. Sorry for that. I will implement more ideal way to check this

**Comment by tchssk** [comment]
Did you remove this commit from `master` branch?
`ghr` fails to craeate release...
@tcnksm

**Comment by tcnksm** [comment]
Oh, really?
It worked in my release, let me check.

**Comment by tchssk** [comment]
Ah `v0.5.2` contains 96bf7bc4c1f85ca1d3b2419cba31ac8a96949594 but `master` doesn't, and I'm using `ghr` via `go get`.

**Comment by tchssk** [comment]
Sorry to bother you again.

`v0.5.2` contains https://github.com/tcnksm/ghr/commit/96bf7bc4c1f85ca1d3b2419cba31ac8a96949594 (https://github.com/tcnksm/ghr/blob/v0.5.2/ghr.go#L70-L87) but `master` doesn't (https://github.com/tcnksm/ghr/blob/master/ghr.go#L70-L83).

Would you rebase `master` branch onto `v0.5.2` tag?
or cherry-pick https://github.com/tcnksm/ghr/commit/96bf7bc4c1f85ca1d3b2419cba31ac8a96949594 into master?

@tcnksm

**Comment by tcnksm** [comment]
Sorry for that. Cherry picked and release `v0.5.3` for that changes.

**Comment by tchssk** [comment]
Thank you!

**Pull request merged**
